@url = https://api.mozambiquehe.re
@api_key =
@platform =
@player_name =
@uid =

#### 認証
GET {{url}}/?auth={{api_key}}

#### ユーザー名によるユーザー情報取得
GET {{url}}/bridge?auth={{api_key}}&player={{player_name}}&platform={{platform}}
Content-Type: text/plain

#### uidによるユーザー情報取得
GET {{url}}/bridge?auth={{api_key}}&uid={{uid}}&platform={{platform}}
Content-Type: text/plain

#### ユーザー名からuiの取得
GET {{url}}/nametouid?auth={{api_key}}&player={{player_name}}&platform={{platform}}
Content-Type: text/plain
